# Generated by Django 3.1.4 on 2021-01-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
