# Generated by Django 3.1.4 on 2021-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210104_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=64)),
                ('orderItems', models.JSONField()),
                ('orderComplete', models.BooleanField(default=False)),
            ],
        ),
    ]
